source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target ‘ChatBot’ do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod 'Hero'
    pod 'Typist'
    pod 'PubNub'
    pod 'SwipeCellKit'
end